import type { Listing, PriceTier } from '@/lib/types';
import { seedProducts } from './catalog';
import { communityId, daysAgo, daysAhead, demoUserId, regionId, slugify } from './helpers';

type ListingSeed = {
  /** Farm or business slug, matching src/lib/db/seed/people.ts. */
  seller: string;
  sellerKind: 'farm' | 'business';
  product: string;
  title: string;
  description: string;
  parish: string;
  community: string;
  /** Whole JMD; converted to minor units on build. */
  price?: number;
  unit: string;
  quantity?: number;
  minOrder?: number;
  pricingMode?: Listing['pricingMode'];
  availability?: Listing['availability'];
  wholesale?: boolean;
  postedDaysAgo: number;
  featured?: boolean;
  tiers?: Array<[minQuantity: number, unitPrice: number, label?: string]>;
};

const LISTINGS: ListingSeed[] = [
  {
    seller: 'green-valley-farm',
    sellerKind: 'farm',
    product: 'scotch-bonnet-pepper',
    title: 'Fresh Scotch Bonnet Pepper',
    description:
      'Reaped to order from our Christiana fields. Firm, well-coloured pepper suitable for sauce production or retail. Bulk pricing available for orders above 50 lbs, and we can hold a standing weekly quantity for regular buyers.',
    parish: 'manchester',
    community: 'Christiana',
    price: 850,
    unit: 'lb',
    quantity: 75,
    minOrder: 5,
    wholesale: true,
    postedDaysAgo: 1,
    featured: true,
    tiers: [
      [1, 85000, 'Retail'],
      [50, 78000, 'Wholesale (50 lb+)'],
      [150, 72000, 'Bulk (150 lb+)'],
    ],
  },
  {
    seller: 'green-valley-farm',
    sellerKind: 'farm',
    product: 'tomato',
    title: 'Plum Tomato — Field Grown',
    description:
      'Field-grown plum tomato, graded and packed in crates. Picked at the breaker stage for buyers who need a few days of shelf life.',
    parish: 'manchester',
    community: 'Christiana',
    price: 420,
    unit: 'lb',
    quantity: 300,
    minOrder: 10,
    wholesale: true,
    postedDaysAgo: 2,
    tiers: [
      [10, 42000, 'Standard'],
      [100, 38000, 'Wholesale (100 lb+)'],
    ],
  },
  {
    seller: 'green-valley-farm',
    sellerKind: 'farm',
    product: 'cucumber',
    title: 'Cucumber — Crate Lots',
    description: 'Straight, uniform cucumber sold by the crate. Reaped Tuesday and Friday mornings.',
    parish: 'manchester',
    community: 'Christiana',
    price: 260,
    unit: 'lb',
    quantity: 180,
    minOrder: 20,
    postedDaysAgo: 4,
  },
  {
    seller: 'green-valley-farm',
    sellerKind: 'farm',
    product: 'sweet-pepper',
    title: 'Sweet Pepper — Mixed Colour',
    description: 'Red, yellow and green sweet pepper. Mixed cases available on request.',
    parish: 'manchester',
    community: 'Christiana',
    price: 620,
    unit: 'lb',
    quantity: 90,
    availability: 'LIMITED',
    postedDaysAgo: 5,
  },
  {
    seller: 'santa-cruz-provision-grounds',
    sellerKind: 'farm',
    product: 'yellow-yam',
    title: 'Yellow Yam — Bulk Supply',
    description:
      'Dug to order. We can load 500 lbs at a time and supply weekly through the season. Wholesalers and exporters welcome.',
    parish: 'st-elizabeth',
    community: 'Santa Cruz',
    price: 380,
    unit: 'lb',
    quantity: 2000,
    minOrder: 100,
    wholesale: true,
    postedDaysAgo: 3,
    featured: true,
    tiers: [
      [100, 38000, 'Wholesale'],
      [500, 34000, 'Bulk (500 lb+)'],
      [1000, 31000, 'Container lots'],
    ],
  },
  {
    seller: 'santa-cruz-provision-grounds',
    sellerKind: 'farm',
    product: 'sweet-potato',
    title: 'Sweet Potato — Red Skin',
    description: 'Red-skin sweet potato, cured and graded. Sold in 50 lb bags.',
    parish: 'st-elizabeth',
    community: 'Santa Cruz',
    price: 300,
    unit: 'lb',
    quantity: 900,
    minOrder: 50,
    wholesale: true,
    postedDaysAgo: 6,
  },
  {
    seller: 'santa-cruz-provision-grounds',
    sellerKind: 'farm',
    product: 'pumpkin',
    title: 'Pumpkin — Field Run',
    description: 'Field-run pumpkin sold by weight. Good keeping quality.',
    parish: 'st-elizabeth',
    community: 'Santa Cruz',
    price: 190,
    unit: 'lb',
    quantity: 600,
    minOrder: 30,
    postedDaysAgo: 9,
  },
  {
    seller: 'clarendon-plains-poultry',
    sellerKind: 'farm',
    product: 'eggs',
    title: 'Fresh Brown Eggs — Daily',
    description:
      'Collected daily from our layer houses. Sold by the dozen or the crate (30 dozen). Standing daily and weekly orders welcome.',
    parish: 'clarendon',
    community: 'May Pen',
    price: 720,
    unit: 'dozen',
    quantity: 400,
    minOrder: 1,
    wholesale: true,
    postedDaysAgo: 0,
    featured: true,
    tiers: [
      [1, 72000, 'Per dozen'],
      [30, 66000, 'Crate (30 dozen)'],
    ],
  },
  {
    seller: 'clarendon-plains-poultry',
    sellerKind: 'farm',
    product: 'live-chicken',
    title: 'Live Broiler Chicken — Weekly Batches',
    description:
      'Broilers batched weekly at 5–6 lbs live weight. Collection from the farm, or delivery within Clarendon and St. Catherine.',
    parish: 'clarendon',
    community: 'May Pen',
    price: 1450,
    unit: 'each',
    quantity: 220,
    minOrder: 10,
    wholesale: true,
    postedDaysAgo: 2,
  },
  {
    seller: 'clarendon-plains-poultry',
    sellerKind: 'farm',
    product: 'dressed-chicken',
    title: 'Dressed Chicken — Whole Birds',
    description: 'Cleaned and bagged whole birds, chilled. Minimum order 20 lbs.',
    parish: 'clarendon',
    community: 'May Pen',
    price: 560,
    unit: 'lb',
    quantity: 500,
    minOrder: 20,
    postedDaysAgo: 3,
  },
  {
    seller: 'spaldings-greenhouse-co-op',
    sellerKind: 'farm',
    product: 'tomato',
    title: 'Greenhouse Tomato — Grade A',
    description:
      'Protected-cultivation tomato with consistent size and colour through the wet season. Packed in single-layer trays for restaurant and hotel buyers.',
    parish: 'manchester',
    community: 'Spaldings',
    price: 580,
    unit: 'lb',
    quantity: 240,
    minOrder: 20,
    wholesale: true,
    postedDaysAgo: 1,
    featured: true,
  },
  {
    seller: 'spaldings-greenhouse-co-op',
    sellerKind: 'farm',
    product: 'lettuce',
    title: 'Crisp Lettuce — Cut Daily',
    description: 'Cut and packed daily. Available all year from protected houses.',
    parish: 'manchester',
    community: 'Spaldings',
    price: 480,
    unit: 'lb',
    quantity: 120,
    minOrder: 5,
    postedDaysAgo: 2,
  },
  {
    seller: 'spaldings-greenhouse-co-op',
    sellerKind: 'farm',
    product: 'pak-choi',
    title: 'Pak Choi',
    description: 'Tender pak choi, cut to order for restaurant buyers.',
    parish: 'manchester',
    community: 'Spaldings',
    price: 350,
    unit: 'lb',
    quantity: 80,
    postedDaysAgo: 7,
  },
  {
    seller: 'trelawny-yam-grounds',
    sellerKind: 'farm',
    product: 'yellow-yam',
    title: 'Yellow Yam — Albert Town',
    description:
      'Dug to order from Albert Town. Consistent supply from October to June. Export-grade selection available.',
    parish: 'trelawny',
    community: 'Albert Town',
    price: 400,
    unit: 'lb',
    quantity: 1500,
    minOrder: 100,
    wholesale: true,
    postedDaysAgo: 5,
  },
  {
    seller: 'trelawny-yam-grounds',
    sellerKind: 'farm',
    product: 'dasheen',
    title: 'Dasheen',
    description: 'Firm dasheen, dug to order. Sold in 50 lb bags.',
    parish: 'trelawny',
    community: 'Albert Town',
    price: 320,
    unit: 'lb',
    quantity: 400,
    minOrder: 50,
    postedDaysAgo: 11,
  },
  {
    seller: 'portland-rain-farm',
    sellerKind: 'farm',
    product: 'banana',
    title: 'Green Banana — Bunches',
    description: 'Sold by the bunch or by weight. Cut to order from the slopes above Fellowship.',
    parish: 'portland',
    community: 'Fellowship',
    price: 150,
    unit: 'lb',
    quantity: 700,
    minOrder: 20,
    postedDaysAgo: 4,
  },
  {
    seller: 'portland-rain-farm',
    sellerKind: 'farm',
    product: 'plantain',
    title: 'Plantain — Green and Turning',
    description: 'Green and turning plantain available. Tell us which stage you need.',
    parish: 'portland',
    community: 'Fellowship',
    price: 230,
    unit: 'lb',
    quantity: 350,
    minOrder: 20,
    postedDaysAgo: 6,
  },
  {
    seller: 'portland-rain-farm',
    sellerKind: 'farm',
    product: 'ackee',
    title: 'Ackee — In Season',
    description: 'Open, properly ripened ackee. Seasonal — ask about current availability.',
    parish: 'portland',
    community: 'Fellowship',
    price: 900,
    unit: 'lb',
    quantity: 60,
    availability: 'SEASONAL',
    postedDaysAgo: 8,
  },
  {
    seller: 'portland-rain-farm',
    sellerKind: 'farm',
    product: 'breadfruit',
    title: 'Breadfruit',
    description: 'Full, mature breadfruit picked to order.',
    parish: 'portland',
    community: 'Fellowship',
    price: 280,
    unit: 'each',
    quantity: 120,
    postedDaysAgo: 13,
  },
  {
    seller: 'yallahs-goat-farm',
    sellerKind: 'farm',
    product: 'goat',
    title: 'Boer-Cross Goat — Live Weight',
    description:
      'Pasture-raised Boer-cross goats sold live. We can arrange dressing through a licensed butcher for buyers who need it.',
    parish: 'st-thomas',
    community: 'Yallahs',
    price: 32000,
    unit: 'each',
    quantity: 18,
    pricingMode: 'NEGOTIABLE',
    postedDaysAgo: 3,
  },
  {
    seller: 'yallahs-goat-farm',
    sellerKind: 'farm',
    product: 'sheep',
    title: 'Sheep — Ready for Market',
    description: 'Pasture-raised sheep, sold live. Price depends on weight and condition.',
    parish: 'st-thomas',
    community: 'Yallahs',
    unit: 'each',
    quantity: 11,
    pricingMode: 'CONTACT_FOR_PRICE',
    postedDaysAgo: 10,
  },
  {
    seller: 'black-river-fish-ponds',
    sellerKind: 'farm',
    product: 'tilapia',
    title: 'Pond-Raised Tilapia — Harvested to Order',
    description:
      'Harvested the morning of collection. Whole fish, ungutted, iced for transport. Bulk orders need three days notice.',
    parish: 'st-elizabeth',
    community: 'Black River',
    price: 680,
    unit: 'lb',
    quantity: 450,
    minOrder: 10,
    wholesale: true,
    postedDaysAgo: 2,
  },
  {
    seller: 'anchovy-apiary',
    sellerKind: 'farm',
    product: 'honey',
    title: 'Raw Honey — 750ml Bottle',
    description:
      'Unheated, unfiltered honey bottled at the apiary. Logwood honey available in the first half of the year; mixed flora the rest.',
    parish: 'st-james',
    community: 'Anchovy',
    price: 2400,
    unit: 'bottle',
    quantity: 140,
    wholesale: true,
    postedDaysAgo: 1,
    featured: true,
    tiers: [
      [1, 240000, 'Single bottle'],
      [12, 215000, 'Case of 12'],
      [48, 195000, 'Bulk (48+)'],
    ],
  },
  {
    seller: 'highgate-spice-gardens',
    sellerKind: 'farm',
    product: 'pimento',
    title: 'Dried Pimento (Allspice)',
    description: 'Sun-dried pimento berries, cleaned and bagged. Available in 25 lb bags.',
    parish: 'st-mary',
    community: 'Highgate',
    price: 1250,
    unit: 'lb',
    quantity: 300,
    minOrder: 25,
    wholesale: true,
    postedDaysAgo: 6,
  },
  {
    seller: 'highgate-spice-gardens',
    sellerKind: 'farm',
    product: 'ginger',
    title: 'Fresh Ginger',
    description: 'Freshly dug ginger, washed and graded.',
    parish: 'st-mary',
    community: 'Highgate',
    price: 980,
    unit: 'lb',
    quantity: 200,
    minOrder: 10,
    postedDaysAgo: 9,
  },
  {
    seller: 'highgate-spice-gardens',
    sellerKind: 'farm',
    product: 'turmeric',
    title: 'Fresh Turmeric',
    description: 'Deep-coloured turmeric rhizome, dug to order.',
    parish: 'st-mary',
    community: 'Highgate',
    price: 860,
    unit: 'lb',
    quantity: 150,
    availability: 'LIMITED',
    postedDaysAgo: 14,
  },
  {
    seller: 'bog-walk-ground-and-citrus',
    sellerKind: 'farm',
    product: 'callaloo',
    title: 'Callaloo — Bundled Fresh',
    description: 'Cut and bundled the morning of delivery. Standing orders welcome.',
    parish: 'st-catherine',
    community: 'Bog Walk',
    price: 180,
    unit: 'bundle',
    quantity: 300,
    minOrder: 10,
    postedDaysAgo: 1,
  },
  {
    seller: 'bog-walk-ground-and-citrus',
    sellerKind: 'farm',
    product: 'escallion',
    title: 'Escallion — Bundles',
    description: 'Clean, well-sized escallion. Sold in bundles, bulk pricing on request.',
    parish: 'st-catherine',
    community: 'Bog Walk',
    price: 210,
    unit: 'bundle',
    quantity: 260,
    minOrder: 10,
    wholesale: true,
    postedDaysAgo: 3,
  },
  {
    seller: 'bog-walk-ground-and-citrus',
    sellerKind: 'farm',
    product: 'cassava',
    title: 'Cassava — Sweet Variety',
    description: 'Sweet cassava dug to order, suitable for bammy production.',
    parish: 'st-catherine',
    community: 'Bog Walk',
    price: 240,
    unit: 'lb',
    quantity: 500,
    minOrder: 50,
    postedDaysAgo: 12,
  },
  {
    seller: 'mavis-bank-hill-farm',
    sellerKind: 'farm',
    product: 'lettuce',
    title: 'Hill-Grown Lettuce',
    description: 'Cool-climate lettuce from 900m. Delivered into Kingston three mornings a week.',
    parish: 'st-andrew',
    community: 'Mavis Bank',
    price: 520,
    unit: 'lb',
    quantity: 90,
    minOrder: 5,
    postedDaysAgo: 0,
  },
  {
    seller: 'mavis-bank-hill-farm',
    sellerKind: 'farm',
    product: 'thyme',
    title: 'Fresh Thyme — Bundles',
    description: 'Aromatic thyme, cut and bundled to order.',
    parish: 'st-andrew',
    community: 'Mavis Bank',
    price: 160,
    unit: 'bundle',
    quantity: 200,
    postedDaysAgo: 2,
  },
  {
    seller: 'mavis-bank-hill-farm',
    sellerKind: 'farm',
    product: 'mint',
    title: 'Fresh Mint',
    description: 'Cut mint for kitchens and bars. Delivered into Kingston.',
    parish: 'st-andrew',
    community: 'Mavis Bank',
    price: 170,
    unit: 'bundle',
    quantity: 120,
    postedDaysAgo: 5,
  },
  {
    seller: 'bluefields-ridge-growers',
    sellerKind: 'farm',
    product: 'string-bean',
    title: 'String Beans — Hotel Grade',
    description: 'Graded string beans packed for hotel kitchens along the west coast.',
    parish: 'westmoreland',
    community: 'Darliston',
    price: 440,
    unit: 'lb',
    quantity: 260,
    minOrder: 20,
    wholesale: true,
    postedDaysAgo: 2,
  },
  {
    seller: 'bluefields-ridge-growers',
    sellerKind: 'farm',
    product: 'cabbage',
    title: 'Cabbage — Heads',
    description: 'Firm cabbage heads, 2–4 lbs each, sold by weight.',
    parish: 'westmoreland',
    community: 'Darliston',
    price: 210,
    unit: 'lb',
    quantity: 800,
    minOrder: 50,
    wholesale: true,
    postedDaysAgo: 4,
  },
  {
    seller: 'bluefields-ridge-growers',
    sellerKind: 'farm',
    product: 'gungo-peas',
    title: 'Gungo Peas — Shelled and In-Pod',
    description: 'Available shelled or in the pod. Seasonal supply, ask for current stock.',
    parish: 'westmoreland',
    community: 'Darliston',
    price: 700,
    unit: 'lb',
    quantity: 180,
    availability: 'SEASONAL',
    postedDaysAgo: 8,
  },
  {
    seller: 'bluefields-ridge-growers',
    sellerKind: 'farm',
    product: 'carrot',
    title: 'Carrot — Washed',
    description: 'Washed and graded carrot in 50 lb bags.',
    parish: 'westmoreland',
    community: 'Darliston',
    price: 290,
    unit: 'lb',
    quantity: 420,
    minOrder: 50,
    postedDaysAgo: 10,
  },
  {
    seller: 'moneague-highland-cattle',
    sellerKind: 'farm',
    product: 'cattle',
    title: 'Weaner Cattle — St. Ann Pasture',
    description:
      'Weaners from a small commercial herd on limestone pasture. Price by animal, depending on weight and condition.',
    parish: 'st-ann',
    community: 'Moneague',
    unit: 'each',
    quantity: 7,
    pricingMode: 'CONTACT_FOR_PRICE',
    postedDaysAgo: 15,
  },
  // ── Businesses: supplies, equipment and services ──────────────────────────
  {
    seller: 'islandwide-agri-supplies',
    sellerKind: 'business',
    product: 'npk-fertilizer',
    title: 'NPK Fertiliser — 50kg Bag',
    description:
      'General-purpose NPK in 50kg bags. Delivery to every parish, with volume pricing for farmer groups.',
    parish: 'st-catherine',
    community: 'Spanish Town',
    price: 9800,
    unit: 'bag',
    quantity: 400,
    wholesale: true,
    postedDaysAgo: 3,
    tiers: [
      [1, 980000, 'Single bag'],
      [10, 930000, '10 bags+'],
      [40, 880000, 'Pallet'],
    ],
  },
  {
    seller: 'islandwide-agri-supplies',
    sellerKind: 'business',
    product: 'layer-feed',
    title: 'Layer Feed — 100lb Bag',
    description: 'Layer ration in 100 lb bags. Bulk pricing for poultry farms.',
    parish: 'st-catherine',
    community: 'Spanish Town',
    price: 7400,
    unit: 'bag',
    quantity: 260,
    wholesale: true,
    postedDaysAgo: 5,
  },
  {
    seller: 'islandwide-agri-supplies',
    sellerKind: 'business',
    product: 'vegetable-seeds',
    title: 'Vegetable Seed — Assorted Packs',
    description: 'Tomato, pepper, cabbage, cucumber and callaloo seed in retail and bulk packs.',
    parish: 'st-catherine',
    community: 'Spanish Town',
    price: 1600,
    unit: 'pack',
    quantity: 900,
    postedDaysAgo: 7,
  },
  {
    seller: 'islandwide-agri-supplies',
    sellerKind: 'business',
    product: 'knapsack-sprayer',
    title: 'Knapsack Sprayer — 16L',
    description: '16 litre knapsack sprayer with spare seals and nozzle set.',
    parish: 'st-catherine',
    community: 'Spanish Town',
    price: 8900,
    unit: 'each',
    quantity: 45,
    postedDaysAgo: 12,
  },
  {
    seller: 'aquaflow-irrigation-jamaica',
    sellerKind: 'business',
    product: 'drip-irrigation-kit',
    title: 'Drip Irrigation Kit — Quarter Acre',
    description:
      'Complete quarter-acre drip kit: mainline, drip tape, filters, fittings and layout plan. Installation quoted separately.',
    parish: 'manchester',
    community: 'Mandeville',
    price: 76000,
    unit: 'kit',
    quantity: 12,
    pricingMode: 'NEGOTIABLE',
    postedDaysAgo: 6,
  },
  {
    seller: 'aquaflow-irrigation-jamaica',
    sellerKind: 'business',
    product: 'water-pump',
    title: 'Surface Water Pump — 2 inch',
    description: '2-inch petrol surface pump suitable for pond and river abstraction.',
    parish: 'manchester',
    community: 'Mandeville',
    price: 54000,
    unit: 'each',
    quantity: 8,
    postedDaysAgo: 9,
  },
  {
    seller: 'clarendon-tractor-services',
    sellerKind: 'business',
    product: 'land-ploughing-service',
    title: 'Ploughing & Harrowing — Per Acre',
    description:
      'Tractor ploughing and harrowing across Clarendon, St. Catherine and south Manchester. Minimum two acres per visit; price varies with land condition.',
    parish: 'clarendon',
    community: 'May Pen',
    price: 18000,
    unit: 'acre',
    minOrder: 2,
    pricingMode: 'NEGOTIABLE',
    postedDaysAgo: 4,
  },
  {
    seller: 'highway-produce-haulage',
    sellerKind: 'business',
    product: 'produce-transport',
    title: 'Produce Transport — Farm to Market',
    description:
      'Refrigerated and open-tray trucks moving produce from farm gate to market, hotel or port. Priced by trip and distance.',
    parish: 'clarendon',
    community: 'May Pen',
    unit: 'trip',
    pricingMode: 'CONTACT_FOR_PRICE',
    postedDaysAgo: 8,
  },
  {
    seller: 'cornwall-veterinary-group',
    sellerKind: 'business',
    product: 'veterinary-visit',
    title: 'Farm Veterinary Visit — Western Parishes',
    description:
      'Scheduled farm visits across St. James, Hanover, Westmoreland and Trelawny. Herd health, vaccination programmes and emergency call-out.',
    parish: 'st-james',
    community: 'Montego Bay',
    price: 12000,
    unit: 'visit',
    pricingMode: 'NEGOTIABLE',
    postedDaysAgo: 11,
  },
];

export type SeededListings = { listings: Listing[]; priceTiers: PriceTier[] };

export function seedListings(): SeededListings {
  const productsBySlug = new Map(seedProducts().map((p) => [p.slug, p]));
  const listings: Listing[] = [];
  const priceTiers: PriceTier[] = [];

  LISTINGS.forEach((seed, index) => {
    const product = productsBySlug.get(seed.product);
    if (!product) {
      throw new Error(`Seed listing references unknown product "${seed.product}"`);
    }

    const sellerId = demoUserId(
      seed.sellerKind === 'farm' ? `user_farmer_${seed.seller}` : `user_business_${seed.seller}`,
    );
    const id = `listing_${index + 1}_${slugify(seed.title)}`.slice(0, 60);
    const pricingMode = seed.pricingMode ?? (seed.wholesale ? 'WHOLESALE' : 'FIXED');

    listings.push({
      id,
      sellerId,
      productId: product.id,
      categoryId: product.categoryId,
      title: seed.title,
      slug: `${slugify(seed.title)}-${slugify(seed.seller)}`,
      description: seed.description,
      imageUrls: [],
      countryCode: 'JM',
      regionId: regionId(seed.parish),
      communityId: communityId(seed.parish, seed.community),
      pricingMode,
      priceMinor: seed.price !== undefined ? seed.price * 100 : undefined,
      currency: 'JMD',
      unit: seed.unit,
      quantity: seed.quantity,
      minOrder: seed.minOrder,
      availability: seed.availability ?? 'IN_STOCK',
      wholesaleAvailable: seed.wholesale ?? false,
      status: 'ACTIVE',
      featuredUntil: seed.featured ? daysAhead(21) : undefined,
      viewCount: 40 + ((index * 37) % 900),
      isDemoData: true,
      createdAt: daysAgo(seed.postedDaysAgo),
      updatedAt: daysAgo(seed.postedDaysAgo),
    });

    (seed.tiers ?? []).forEach((tier, tierIndex) => {
      priceTiers.push({
        id: `tier_${id}_${tierIndex}`,
        listingId: id,
        minQuantity: tier[0],
        unitPrice: tier[1],
        label: tier[2],
      });
    });
  });

  return { listings, priceTiers };
}
